### ISSUE TITLE
How did you get your jankyborders config to work?

### ISSUE THREAD

**Issue by beobuild** [breuerfelix/dotfiles#5]
Hi there,
I'm currently using your dotfiles as reference to make my own df, but I'm not pretty sure about this file: `darwin/borders.nix`
Could you explain how did you start the `bordersrc` file from the Nix store?

Many thanks! <3

**Comment by breuerfelix** [comment]
@emladevops great to hear! i am currently moving to a new mac, so in the past week my dotfiles were moving a lot, just as a note for you :) i also think about removing the sole linux part completely. currently there is a lot i3 stuff in there and i think i am not moving back to linux anywhere soon. so maybe next week the repo will look way more cleaner :)

but back to the topic, since borders does not have a nix module i use the brew service for borders. just `brew services start borders` once, and this will persist during boot and will automatically start borders when restarting your mac.

**Comment by beobuild** [comment]
thanks for your response and assistance!
